homeassistant:
  # Name of the location where Home Assistant is running
  name: Wolfsbau
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude 
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 273
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Zurich
  # Customization file
  customize: !include customize.yaml

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Text to speech
tts:
  - platform: google
    language: 'de'

# Cloud
cloud:

group: !include groups.yaml
automation: !include_dir_list automation
script: !include scripts.yaml

#Custom

device_tracker:
  - platform: unifi
    username: Nyno
    password: !secret unifi-password
    host: 192.168.1.2
    port: 8443
    verify_ssl: false
    detection_time: 20

light:
  - platform: lifx
    broadcast: 192.168.1.255
 
  - platform: nanoleaf_flavio
    host: 192.168.1.121
    token: !secret nanolef_flavio_token

sensor:
  - platform: speedtest
    monitored_conditions:
      - ping
      - download
      - upload
  - platform: time_date
    display_options:
    - 'time'
    - 'date'

  - platform: darksky
    api_key: !secret darksky_api 
    monitored_conditions:
    - summary
    - temperature
    - temperature_max
    - temperature_min
    - wind_speed
    update_interval:
        # At least one of these must be specified:
        days: 0
        hours: 0
        minutes: 15
        seconds: 0
        milliseconds: 0

  - platform: moon

  - platform: swiss_public_transport
    from: !secret tram_from_1
    to: !secret tram_to_1

  - platform: coinmarketcap
    currency_id: 1
    display_currency: CHF

  - platform: coinmarketcap
    currency_id: 1027
    display_id: CHF

  - platform: twitch
    client_id: yuilz2a33fhr9r4mm9e9ypo0be1rnk
    channels:
    - kotton

binary_sensor:
  - platform: iss
    show_on_map: true

media_player:
  - platform: samsungtv
    host: 192.168.1.105

weblink:
  entities:
    - name: unifi
      url: !secret unifi_url
      icon: mdi:router-wireless
    - name: nextcloud
      url: !secret nextcloud_url
      icon: mdi:cloud

